import Head from "next/head"
import Link from "next/link"
import FlatBorderLayout from "@components/layouts/flat-border"
import Header from "@components/header"
import RouteViewer from "@components/route-viewer"
import { AboutMe, SimpleSpaghettio } from "@components/articles"
import { useMemo } from "react"

const articles = [
  {
    path: "/",
    label: "about me",
    component: <AboutMe />,
  },
  {
    path: "/#simple-spaghettio",
    label: "simple-spaghett.io",
    component: <SimpleSpaghettio />,
  },
]

export default function Home() {
  const sidebarArticles = useMemo(
    () => articles.filter((a) => a.path !== "/"),
    [],
  )

  return (
    <>
      <Head>
        <title>Neil Smith | Frontend Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="#main" className="sr-only focus:not-sr-only">
        Skip to main content
      </a>
      <FlatBorderLayout
        header={
          <header role="banner">
            <Header />
          </header>
        }
        body={
          <main
            id="main"
            role="main"
            className="grid grid-cols-3 gap-12 text-lg font-light lg:gap-28 xl:gap-36 md:text-xl"
          >
            <div className="col-span-3 md:col-span-2">
              <RouteViewer>
                {articles.map((article) => (
                  <RouteViewer.Route key={article.path} path={article.path}>
                    {article.component}
                  </RouteViewer.Route>
                ))}
              </RouteViewer>
            </div>
            <aside className="col-span-3 md:col-span-1">
              <h2 className="mb-8 text-5xl font-thin md:mt-1 md:mb-6 lg:mb-8 md:text-4xl lg:text-5xl">
                projects
              </h2>
              <nav aria-label="Projects Navigation" role="navigation">
                <ul className="space-y-6">
                  {sidebarArticles.map((article) => (
                    <li key={article.path}>
                      <Link
                        href={article.path}
                        className="underline transition-colors duration-200 transform underline-offset-4"
                      >
                        {article.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </nav>
            </aside>
          </main>
        }
      />
    </>
  )
}
