import Head from "next/head"
import Header from "@components/header"
import Link from "next/link"

export default function Home() {
  return (
    <>
      <style global jsx>{`
        html,
        body,
        div#__next {
          height: 100%;
        }
      `}</style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="#main" className="sr-only focus:not-sr-only">
        Skip to main content
      </a>
      <div className="flex items-baseline justify-center h-full mt-6 md:mt-0 md:items-center">
        <div className="container mx-auto">
          {/*the border/svg/decoration would either wrap or be sibilings to this border element */}
          <div className="p-12 border">
            <div className="mb-14">
              <Header />
            </div>
            <main
              id="main"
              role="main"
              className="grid grid-cols-3 gap-12 text-lg font-light lg:gap-28 xl:gap-36 md:text-xl"
            >
              <div className="col-span-3 md:col-span-2">
                <h2 className="mb-8 text-6xl font-thin lg:text-8xl">
                  about me
                </h2>
                <div className="flex gap-8">
                  <div className="border-l-2" />
                  <div className="space-y-4">
                    <p>
                      Irure laboris consequat excepteur sint pariatur
                      reprehenderit adipisicing. Laboris incididunt velit
                      eiusmod amet non voluptate. Eu dolor laborum ea aliquip
                      cupidatat consectetur. Minim cupidatat mollit Lorem veniam
                      exercitation pariatur velit tempor.
                    </p>
                    <p>
                      Eu dolor laborum ea aliquip cupidatat consectetur. Elit
                      pariatur nisi esse do. Qui laboris deserunt excepteur
                      consectetur do dolor sit adipisicing amet reprehenderit
                      laborum irure nulla..
                    </p>
                    <div className="pt-8 pb-5">
                      <ul className="flex gap-8">
                        <li>
                          <Link
                            href="/"
                            className="px-8 py-4 text-lg font-medium leading-normal text-white uppercase border"
                          >
                            My CV
                          </Link>
                        </li>
                        <li>
                          <Link
                            href="/"
                            className="px-8 py-4 text-lg font-medium leading-normal text-white uppercase border"
                          >
                            Contact Me
                          </Link>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-span-3 md:col-span-1">
                <h2 className="mb-8 text-5xl font-thin md:mt-4 lg:mt-8 lg:mb-12 md:text-4xl lg:text-5xl">
                  projects
                </h2>
                <nav aria-label="Projects Navigation">
                  <ul className="space-y-6">
                    <li>
                      <Link
                        href="#universe"
                        className="underline underline-offset-8"
                      >
                        univer.se
                      </Link>
                    </li>
                    <li>
                      <Link
                        href="#simple-spaghettio"
                        className="underline underline-offset-8"
                      >
                        simple-spaghett.io
                      </Link>
                    </li>
                    <li>
                      <Link
                        href="#brsl-events"
                        className="underline underline-offset-8"
                      >
                        brsl events
                      </Link>
                    </li>
                    <li>
                      <Link
                        href="#kysek"
                        className="underline underline-offset-8"
                      >
                        kysek
                      </Link>
                    </li>
                  </ul>
                </nav>
              </div>
            </main>
          </div>
        </div>
      </div>
    </>
  )
}
