import Head from "next/head"
import Layout from "@components/layouts/basic-border"
import { ReactElement } from "react"
import AboutMe from "@components/articles/about-me"
import FixedHeightRouteViewer from "@components/fixed-height-route-viewer"
import SimpleSpaghettio from "@components/articles/simple-spaghettio"
import CaptainHooks from "@components/articles/captain-hooks"
import { GetServerSideProps } from "next"

/**
 * TODO:
 * - create an 'article' component which wraps children in an animation
 */

export const getServerSideProps: GetServerSideProps = async (context) => {
  const theme = context.req.cookies["theme"] ?? null

  return {
    props: {
      theme,
    },
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Neil Smith | Frontend Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FixedHeightRouteViewer>
        {(updateHeight) => (
          <>
            <FixedHeightRouteViewer.Route path="/" reportHeight={updateHeight}>
              <AboutMe />
            </FixedHeightRouteViewer.Route>
            <FixedHeightRouteViewer.Route
              path="/#simple-spaghettio"
              reportHeight={updateHeight}
            >
              <SimpleSpaghettio />
            </FixedHeightRouteViewer.Route>
            <FixedHeightRouteViewer.Route
              path="/#captain-hooks"
              reportHeight={updateHeight}
            >
              <CaptainHooks />
            </FixedHeightRouteViewer.Route>
          </>
        )}
      </FixedHeightRouteViewer>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}
